---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      github-actions-dependencies:
        patterns:
          - '*'
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      python-dependencies:
        patterns:
          - '*'
    labels:
      - dependencies
      - python

  - package-ecosystem: terraform
    directory: /modules
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      terraform-modules-dependencies:
        patterns:
          - '*'
    labels:
      - dependencies
      - terraform

  - package-ecosystem: terraform
    directory: /examples/deployments
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      terraform-examples-dependencies:
        patterns:
          - '*'
    labels:
      - dependencies
      - terraform

  - package-ecosystem: docker
    directory: /.docker
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      docker-dependencies:
        patterns:
          - '*'
    labels:
      - dependencies
      - docker
