---
# yamllint disable rule:comments
# yamllint disable rule:truthy
name: Cloud Custodian

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

permissions:
  contents: read # Required to checkout policy files.

concurrency:
  group: cloud-custodian
  cancel-in-progress: false

jobs:
  run:
    name: Run policies
    runs-on: k8s
    permissions:
      contents: read # Required to checkout policy files.
      id-token: write # Required to assume the AWS policy role through OIDC.
    env:
      AWS_REGION: ${{ vars.AWS_REGION || 'eu-west-1' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

      - name: Run policies
        shell: bash
        run: custodian run --output-dir output --region "$AWS_REGION" policies

      - name: Upload policy output
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: cloud-custodian-output
          path: output
          if-no-files-found: ignore
