run "platform_ec2_deployment_interface_contract" {
  command = plan

  module {
    source = "../../../tests/tofu/module_interface_contract"
  }

  variables {
    module_path = "."
    expected_input_variables = [
      "aws_region",
      "network_configs",
      "runner_configs",
      "tenant_configs",
    ]
    expected_output_values = [
      "ec2_runners_ami_name_map",
      "ec2_runners_arn_map",
      "ec2_runners_labels_map",
      "event_bus_name",
      "subnet_cidr_blocks",
      "webhook_endpoint",
    ]
    expected_interface_literals = [
      "variable \"aws_region\"",
      "type        = string",
      "description = \"Assuming single region for now.\"",
      "variable \"network_configs\"",
      "type = object({",
      "vpc_id            = string",
      "subnet_ids        = list(string)",
      "lambda_vpc_id     = string",
      "lambda_subnet_ids = list(string)",
      "variable \"runner_configs\"",
      "env                       = string",
      "prefix                    = string",
      "ghes_url                  = string",
      "log_level                 = string",
      "logging_retention_in_days = string",
      "github_app = object({",
      "key_base64     = string",
      "id             = string",
      "webhook_secret = string",
      "runner_iam_role_managed_policy_arns = list(string)",
      "runner_specs = map(object({",
      "tags = optional(map(string), {})",
      "runner = object({",
      "os                     = string",
      "architecture           = string",
      "boot_time_in_minutes   = optional(number, 5)",
      "disable_default_labels = optional(bool, false)",
      "extra_labels           = optional(list(string), [])",
      "group_name             = optional(string, \"Default\")",
      "name_prefix            = optional(string, \"\")",
      "run_as_root            = optional(bool, false)",
      "run_as                 = optional(string, \"ec2-user\")",
      "maximum_count          = number",
      "ephemeral              = optional(bool, false)",
      "jit_config_enabled     = optional(bool, null)",
      "auto_update_disabled   = optional(bool, false)",
      "hooks = optional(object({",
      "job_started   = optional(string, \"\")",
      "job_completed = optional(string, \"\")",
      "iam = optional(object({",
      "role = optional(object({",
      "managed_policy_arns          = optional(map(string), {})",
      "additional_trust_policy_json = optional(string, null)",
      "path                         = optional(string, null)",
      "permissions_boundary         = optional(string, null)",
      "github = optional(object({",
      "organization_runners = optional(bool, false)",
      "lambda = optional(object({",
      "queue = optional(object({",
      "delay_webhook_event            = optional(number, 30)",
      "job_queue_retention_in_seconds = optional(number, 86400)",
      "event_source_mapping = optional(object({",
      "batch_size                         = optional(number, null)",
      "maximum_batching_window_in_seconds = optional(number, null)",
      "redrive_build_queue = optional(object({",
      "enabled         = bool",
      "maxReceiveCount = number",
      "scale_up = optional(object({",
      "reserved_concurrent_executions = optional(number, 1)",
      "job_queued_check_enabled       = optional(bool, null)",
      "scale_down = optional(object({",
      "schedule_expression             = optional(string, \"cron(*/5 * * * ? *)\")",
      "minimum_running_time_in_minutes = optional(number, null)",
      "idle_config = optional(list(object({",
      "cron             = string",
      "timeZone         = string",
      "idleCount        = number",
      "evictionStrategy = optional(string, \"oldest_first\")",
      "pool = optional(object({",
      "config = optional(list(object({",
      "schedule_expression          = string",
      "schedule_expression_timezone = optional(string)",
      "size                         = number",
      "runner_owner = optional(string, null)",
      "job_retry = optional(object({",
      "enabled          = optional(bool, false)",
      "delay_in_seconds = optional(number, 300)",
      "delay_backoff    = optional(number, 2)",
      "max_attempts     = optional(number, 1)",
      "memory_size                    = optional(number, 256)",
      "timeout                        = optional(number, 30)",
      "ssm = optional(object({",
      "kms_key = optional(object({",
      "parameters = optional(object({",
      "housekeeper = optional(object({",
      "observability = optional(object({",
      "logs = optional(object({",
      "blocked_keys = optional(list(string), [])",
      "restricted_keys = optional(map(object({",
      "allowed = optional(list(string), [])",
      "denied  = optional(list(string), [])",
      "max     = optional(string, null)",
      "compute_provider = object({",
      "ec2 = optional(object({",
      "metadata_options = optional(object({",
      "instance_metadata_tags      = optional(string, \"enabled\")",
      "http_endpoint               = optional(string, \"enabled\")",
      "http_tokens                 = optional(string, \"required\")",
      "http_put_response_hop_limit = optional(number, 1)",
      "ami = optional(object({",
      "filter = optional(map(list(string)), { state = [\"available\"] })",
      "owners = optional(list(string), [\"amazon\"])",
      "id_ssm_parameter = optional(object({",
      "kms_key = optional(object({",
      "arn = string",
      "block_device_mappings = optional(list(object({",
      "delete_on_termination      = optional(bool, true)",
      "device_name                = optional(string, \"/dev/xvda\")",
      "encrypted                  = optional(bool, true)",
      "iops                       = optional(number)",
      "kms_key_id                 = optional(string)",
      "snapshot_id                = optional(string)",
      "throughput                 = optional(number)",
      "volume_initialization_rate = optional(number)",
      "volume_size                = number",
      "volume_type                = optional(string, \"gp3\")",
      "create_service_linked_role_spot = optional(bool, false)",
      "credit_specification            = optional(string, null)",
      "ebs_optimized                   = optional(bool, false)",
      "cloudwatch_agent = optional(object({",
      "config  = optional(string, null)",
      "binaries_syncer = optional(object({",
      "detailed_monitoring_enabled = optional(bool, false)",
      "ssm_enabled                 = optional(bool, false)",
      "user_data = optional(object({",
      "enabled               = optional(bool, true)",
      "template              = optional(string, null)",
      "content               = optional(string, null)",
      "pre_install           = optional(string, \"\")",
      "post_install          = optional(string, \"\")",
      "debug_logging_enabled = optional(bool, false)",
      "instance_allocation_strategy  = optional(string, \"lowest-price\")",
      "instance_max_spot_price       = optional(string, null)",
      "instance_target_capacity_type = optional(string, \"spot\")",
      "instance_type_priorities      = optional(map(number), null)",
      "instance_types                = list(string)",
      "additional_security_group_ids = optional(list(string), [])",
      "instance_profile = optional(object({",
      "name = string",
      "enable_on_demand_failover_for_errors = optional(list(string), [])",
      "scale_errors = optional(list(string), [",
      "subnet_ids = optional(list(string), null)",
      "vpc_id     = optional(string, null)",
      "cpu_options = optional(object({",
      "core_count            = optional(number)",
      "threads_per_core      = optional(number)",
      "amd_sev_snp           = optional(string)",
      "nested_virtualization = optional(string)",
      "placement = optional(object({",
      "affinity                = optional(string)",
      "availability_zone       = optional(string)",
      "group_id                = optional(string)",
      "group_name              = optional(string)",
      "host_id                 = optional(string)",
      "host_resource_group_arn = optional(string)",
      "spread_domain           = optional(string)",
      "tenancy                 = optional(string)",
      "partition_number        = optional(number)",
      "license_specifications = optional(list(object({",
      "license_configuration_arn = string",
      "use_dedicated_host = optional(bool, false)",
      "log_files = optional(list(object({",
      "log_group_name   = string",
      "prefix_log_group = bool",
      "file_path        = string",
      "log_stream_name  = string",
      "log_class        = optional(string, \"STANDARD\")",
      "tags = optional(map(string), {})",
      "matcherConfig = object({",
      "labelMatchers           = list(list(string))",
      "exactMatch              = optional(bool, false)",
      "bidirectionalLabelMatch = optional(bool, false)",
      "priority                = optional(number, 999)",
      "enableDynamicLabels     = optional(bool, false)",
      "awsDynamicLabelsPolicy = optional(object({",
      "for runner_config in values(var.runner_configs.runner_specs) :",
      "variable \"tenant_configs\"",
      "ecr_registries = list(string)",
      "tags           = map(string)",
      "ec2_runner_configs = var.runner_configs.runner_specs",
      "effective_runner_users = {",
      "effective_runner_home_directories = {",
      "forge_runner_hook_job_started = {",
      "runner_hook_job_started = {",
      "textencodebase64(runner_config.runner.hooks.job_started, \"UTF-16LE\")",
      "base64encode(runner_config.runner.hooks.job_started)",
      "length(runner_config.compute_provider.ec2[*]) == 1",
      "length(runner_config.compute_provider.ec2.ami[*]) == 1",
      "&& length(runner_config.compute_provider.ec2.ami.id_ssm_parameter[*]) == 0,",
      "error_message = \"Forge EC2 runner_specs must configure a module-managed ami block; ami = null and external ami.id_ssm_parameter ownership are not supported.\"",
      "try(!runner_config.compute_provider.ec2.user_data.debug_logging_enabled, false)",
      "error_message = \"Forge EC2 runner_specs do not support user_data.debug_logging_enabled while the upstream v1 adapter is active.\"",
      "length(runner_config.compute_provider.ec2.instance_profile[*]) == 0",
      "&& length(runner_config.runner.iam.role[*]) == 0,",
      "error_message = \"Forge EC2 runner_specs do not support external runner.iam.role or compute_provider.ec2.instance_profile ownership while the upstream v1 adapter is active.\"",
      "length(runner_config.runner.tags) == 0",
      "&& length(runner_config.observability.logs.tags) == 0",
      "error_message = \"Forge EC2 runner_specs only support compute_provider.ec2.tags while the upstream v1 adapter is active; all other v2 per-lane tag maps must remain empty.\"",
      "runner_config.runner.iam.additional_trust_policy_json == null",
      "&& runner_config.job_retry.lambda.reserved_concurrent_executions == 1",
      "&& runner_config.ssm.kms_key == null",
      "error_message = \"Forge EC2 runner_specs do not support per-lane IAM trust/path/boundary, non-default job-retry Lambda reserved concurrency, or per-lane SSM KMS keys while the upstream v1 adapter is active.\"",
      "active_ec2_subnet_ids = toset(flatten([",
      "legacy_runner_labels = {",
      "matcher_index, labels in runner_config.matcherConfig.labelMatchers",
      "!contains(local.legacy_runner_labels[key], label)",
      "ec2_default_ami_filters = {",
      "windows = { name = [\"Windows_Server-2022-English-Full-ECS_Optimized-*\"] }",
      "linux   = runner_config.runner.architecture == \"arm64\" ? { name = [\"al2023-ami-2023.*-kernel-6.*-arm64\"] } : { name = [\"al2023-ami-2023.*-kernel-6.*-x86_64\"] }",
      "osx     = runner_config.runner.architecture == \"arm64\" ? { name = [\"amzn-ec2-macos-15.*-arm64\"] } : { name = [\"amzn-ec2-macos-15.*\"] }",
      "ec2_update_runner_ami_map = {",
      "local.ec2_default_ami_filters[key],",
      "ami = runner_config.compute_provider.ec2.ami == null ? null : merge(",
      "runner_config.compute_provider.ec2.ami.filter,",
      "ami_filter      = local.ec2_compute_provider[key].ami.filter",
      "ami_owners      = local.ec2_compute_provider[key].ami.owners",
      "runner_ami_map = local.ec2_update_runner_ami_map",
      "key => merge(",
      "runner_config.compute_provider.ec2,",
      "log_files = coalesce(runner_config.compute_provider.ec2.log_files, local.forge_ec2_log_files[key])",
      "tags      = merge(var.tenant_configs.tags, runner_config.compute_provider.ec2.tags)",
      "multi_runner_config_v1 = {",
      "runner_os                     = runner_config.runner.os",
      "runner_metadata_options       = local.ec2_compute_provider[key].metadata_options",
      "runner_boot_time_in_minutes   = runner_config.runner.boot_time_in_minutes",
      "enable_organization_runners   = runner_config.github.organization_runners",
      "id_ssm_parameter_arn = try(local.ec2_compute_provider[key].ami.id_ssm_parameter.arn, null)",
      "kms_key_arn          = try(local.ec2_compute_provider[key].ami.kms_key.arn, null)",
      "enable_cloudwatch_agent              = local.ec2_compute_provider[key].cloudwatch_agent.enabled",
      "enable_userdata                      = local.ec2_compute_provider[key].user_data.enabled",
      "runner_additional_security_group_ids = local.ec2_compute_provider[key].additional_security_group_ids",
      "runner_log_files                     = local.ec2_compute_provider[key].log_files",
      "runner_ec2_tags                      = local.ec2_compute_provider[key].tags",
      "runner_home    = local.effective_runner_home_directories[key]",
      "delay_webhook_event                                            = runner_config.queue.delay_webhook_event",
      "scale_up_reserved_concurrent_executions                        = runner_config.scale_up.reserved_concurrent_executions",
      "idle_config                                                    = runner_config.scale_down.idle_config",
      "pool_config                                                    = runner_config.pool.config",
      "enable             = runner_config.job_retry.enabled",
      "lambda_memory_size = runner_config.job_retry.lambda.memory_size",
      "runner_hook_job_started   = local.runner_hook_job_started[key]",
      "runner_iam_role_managed_policy_arns = concat(",
      "for policy_name in sort(keys(runner_config.runner.iam.managed_policy_arns)) :",
      "matcherConfig = runner_config.matcherConfig",
      "redrive_build_queue = runner_config.queue.redrive_build_queue",
      "multi_runner_config = local.multi_runner_config_v1",
      "output \"ec2_runners_arn_map\"",
      "for runner_key, runner in module.runners.runners_map : runner_key => runner.role_runner[0].arn",
      "output \"ec2_runners_ami_name_map\"",
      "data.aws_ami.runner_ami[runner_key].name",
      "output \"ec2_runners_labels_map\"",
      "output \"event_bus_name\"",
      "value       = module.runners.webhook.eventbridge.event_bus.name",
      "output \"subnet_cidr_blocks\"",
      "value       = { for id, subnet in data.aws_subnet.runner_subnet : id => subnet.cidr_block }",
      "output \"webhook_endpoint\"",
      "value       = module.runners.webhook.endpoint",
    ]
  }

  assert {
    condition     = length(output.missing_input_variables) == 0
    error_message = "Interface contract is missing input variables: ${join(", ", output.missing_input_variables)}"
  }

  assert {
    condition     = length(output.unexpected_input_variables) == 0
    error_message = "Interface contract has unexpected input variables: ${join(", ", output.unexpected_input_variables)}"
  }

  assert {
    condition     = length(output.missing_output_values) == 0
    error_message = "Interface contract is missing outputs: ${join(", ", output.missing_output_values)}"
  }

  assert {
    condition     = length(output.unexpected_output_values) == 0
    error_message = "Interface contract has unexpected outputs: ${join(", ", output.unexpected_output_values)}"
  }

  assert {
    condition     = length(output.missing_interface_literals) == 0
    error_message = "Interface contract is missing expected variable/output source lines: ${join(", ", output.missing_interface_literals)}"
  }

  assert {
    condition = (
      output.expected_input_variable_count == 4
      && output.expected_output_value_count == 6
      && output.expected_interface_literal_count == 257
    )
    error_message = "Interface contract counts must remain pinned for inputs, outputs, and source literals."
  }
}
