locals {
  github_runner_module_source = get_env("GITHUB_RUNNER_MODULE_SOURCE", "git::https://github.com/github-aws-runners/terraform-aws-github-runner.git//modules/multi-runner?ref=v7.8.0")
}

generate "github_runner_source_override" {
  path      = "../ec2_deployment/runner_source_override.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
# Generated by Terragrunt. This file is written into .terragrunt-cache so the
# nested ec2_deployment module can override terraform-aws-github-runner source.
module "runners" {
  source = ${jsonencode(local.github_runner_module_source)}
}
EOF
}

# We use for enabling safety hooks. They're in place to prevent an accident "tf
# run-all apply" for a non-dev environment.
terraform {
  # Make it difficult to change or destroy resources in non-dev environments.
  before_hook "before_hook" {
    commands = ["apply", "plan", "destroy"]
    execute = [
      "/bin/bash", "-c",
      "${get_parent_terragrunt_dir()}/safety_hook.sh \"${get_parent_terragrunt_dir()}\" \"${get_terragrunt_dir()}\""
    ]
  }

  # Placeholder (no-op); might use this in the future.
  after_hook "after_hook" {
    commands     = ["apply", "plan"]
    execute      = ["/bin/bash", "-c", ":"]
    run_on_error = true
  }
}
