---
host_groups:
  mac2:
    name: <HOST_GROUP_NAME>                 # e.g., mac2-servers
    host_instance_type: <HOST_INSTANCE_TYPE>  # e.g., mac2.metal
    hosts:
      - name: <HOST_NAME>                   # e.g., mac2-server-1-eu-west-1a
        availability_zone: <AVAILABILITY_ZONE>  # e.g., eu-west-1a
