---
# yamllint disable rule:comments
# yamllint disable rule:truthy
name: Reusable Forge example category

on:
  workflow_call:
    inputs:
      example-folder:
        type: string
        required: true
      operation:
        type: string
        required: true
      terragrunt-command:
        type: string
        required: true
      ref:
        type: string
        required: false
        default: main

permissions:
  contents: read

jobs:
  discover:
    name: Discover ${{ inputs.example-folder }} ${{ inputs.operation }} units
    runs-on: k8s
    outputs:
      modules: ${{ steps.discover.outputs.terragrunt-modules }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Discover Terragrunt modules
        id: discover
        uses: ./.github/actions/terragrunt-deployment-action
        with:
          example-folder: ${{ inputs.example-folder }}
          run-type: discover
          terragrunt-command: ${{ inputs.terragrunt-command }}
          ref: ${{ inputs.ref }}

  run:
    name: ${{ inputs.operation }} ${{ inputs.example-folder }} - ${{ matrix.module.path }}
    needs:
      - discover
    runs-on: k8s
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        module: ${{ fromJSON(needs.discover.outputs.modules) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run Terragrunt
        uses: ./.github/actions/terragrunt-deployment-action
        with:
          example-folder: ${{ inputs.example-folder }}
          run-type: ${{ inputs.operation }}
          terragrunt-unit-path: ${{ matrix.module.path }}
          ref: ${{ inputs.ref }}
