run "platform_forge_runners_interface_contract" {
  command = plan

  module {
    source = "../../../tests/tofu/module_interface_contract"
  }

  variables {
    module_path = "."
    expected_input_variables = [
      "arc_deployment_specs",
      "aws_profile",
      "aws_region",
      "default_tags",
      "deployment_config",
      "ec2_deployment_specs",
      "github_webhook_relay",
      "log_level",
      "logging_retention_in_days",
      "tags",
    ]
    expected_output_values = [
      "forge_core",
      "forge_github_actions_job_logs",
      "forge_github_app",
      "forge_runners",
      "forge_webhook_relay",
    ]
    expected_interface_literals = [
      "variable \"arc_deployment_specs\"",
      "type = object({",
      "cluster_name    = string",
      "migrate_cluster = optional(bool, false)",
      "karpenter_node_pool = optional(object({",
      "requirements = optional(list(object({",
      "min_values = optional(number)",
      "cpu_limit            = optional(number, 100)",
      "consolidation_policy = optional(string, \"WhenEmptyOrUnderutilized\")",
      "consolidate_after    = optional(string, \"1m\")",
      "runner_specs = map(object({",
      "runner_size = object({",
      "max_runners = number",
      "min_runners = number",
      "scale_set_name   = string",
      "scale_set_type   = string",
      "scale_set_labels = list(string)",
      "container_images = optional(object({",
      "actions_runner = optional(string, \"ghcr.io/actions/actions-runner:latest\")",
      "busybox        = optional(string, \"public.ecr.aws/docker/library/busybox:stable\")",
      "dind_rootless  = optional(string, \"public.ecr.aws/docker/library/docker:dind-rootless\")",
      "}), {})",
      "container_limits_cpu         = string",
      "container_limits_memory      = string",
      "container_requests_cpu       = string",
      "container_requests_memory    = string",
      "volume_requests_storage_size = string",
      "volume_requests_storage_type = string",
      "}))",
      "description = <<-EOT",
      "Deployment configuration for Azure Container Apps (ARC) runners.",
      "Top-level fields:",
      "- cluster_name   : Name of the EKS cluster used for ARC runners.",
      "- migrate_cluster: Optional flag to indicate a one-time migration or",
      "blue/green cutover of the ARC runner cluster.",
      "- runner_specs   : Map of ARC runner pool keys to their sizing and",
      "container resource settings.",
      "runner_specs[*] object fields:",
      "- runner_size.max_runners: Maximum concurrent ARC runners for this pool.",
      "- runner_size.min_runners: Minimum number of warm runners.",
      "- scale_set_name         : Logical name for the scale set / pool.",
      "- scale_set_type         : Backing type for the scale set (for example,",
      "kubernetes or containerapp, depending on integration).",
      "- scale_set_labels       : GitHub runner labels advertised by this ARC",
      "scale set.",
      "- container_images            : Container images used by the ARC runner,",
      "sidecars, and DinD containers.",
      "- container_limits_cpu        : CPU limit for the runner container.",
      "- container_limits_memory     : Memory limit for the runner container.",
      "- container_requests_cpu      : CPU request (baseline reservation).",
      "- container_requests_memory   : Memory request (baseline reservation).",
      "- volume_requests_storage_size: Size of attached storage for the runner.",
      "- volume_requests_storage_type: Storage class or type for attached volume.",
      "EOT",
      "variable \"aws_profile\"",
      "type        = string",
      "description = \"AWS profile to use.\"",
      "variable \"aws_region\"",
      "description = \"AWS region where Forge runners and supporting infrastructure are deployed.\"",
      "variable \"default_tags\"",
      "type        = map(string)",
      "description = \"A map of tags to apply to resources.\"",
      "variable \"deployment_config\"",
      "deployment_prefix = string",
      "secret_suffix     = string",
      "env               = string",
      "github_app = object({",
      "id              = string",
      "client_id       = string",
      "installation_id = string",
      "name            = string",
      "github = object({",
      "ghes_org             = string",
      "ghes_url             = string",
      "repository_selection = string",
      "runner_group_name    = string",
      "tenant = object({",
      "name                         = string",
      "iam_roles_to_assume          = optional(list(string), [])",
      "ecr_registries               = optional(list(string), [])",
      "github_logs_reader_role_arns = optional(list(string), [])",
      "validation {",
      "condition     = contains([\"all\", \"selected\"], var.deployment_config.github.repository_selection)",
      "error_message = \"repository_selection must be 'all' or 'selected'.\"",
      "condition     = trimspace(var.deployment_config.github.ghes_org) != \"\"",
      "error_message = \"ghes_org must be non-empty.\"",
      "High-level deployment configuration for a Forge runner installation.",
      "- deployment_prefix: Prefix used when naming resources (for example,",
      "log groups, KMS keys, and SSM parameters).",
      "- env              : Logical environment name (for example, dev, stage,",
      "prod). Used for tagging and dashboards.",
      "github_app object:",
      "- id             : Numeric GitHub App ID.",
      "- client_id      : OAuth client ID for the app.",
      "- installation_id: GitHub App installation ID for this tenant.",
      "- name           : GitHub App name, used to build URLs and logs.",
      "github object:",
      "- ghes_org            : GitHub organization that owns the repos where",
      "runners will be used.",
      "- ghes_url            : GitHub.com or GHES base URL. Empty string implies",
      "public github.com.",
      "- repository_selection: Scope for runners (all or selected repositories).",
      "- runner_group_name   : GitHub runner group to attach new runners to.",
      "tenant object:",
      "- name                        : Tenant identifier used in naming and",
      "tagging.",
      "- iam_roles_to_assume         : Optional list of IAM role ARNs that",
      "runners are allowed to assume for workload execution.",
      "- ecr_registries              : Optional list of ECR registry URLs that",
      "runners may need to pull images from.",
      "- github_logs_reader_role_arns: Optional list of IAM roles that can read",
      "GitHub Actions logs for this tenant.",
      "variable \"ec2_deployment_specs\"",
      "lambda_subnet_ids = list(string)",
      "subnet_ids        = list(string)",
      "lambda_vpc_id     = string",
      "vpc_id            = string",
      "runner_specs = map(object({",
      "tags = optional(map(string), {})",
      "runner = object({",
      "os                     = string",
      "architecture           = string",
      "boot_time_in_minutes   = optional(number, 5)",
      "disable_default_labels = optional(bool, false)",
      "extra_labels           = optional(list(string), [])",
      "group_name             = optional(string, \"Default\")",
      "name_prefix            = optional(string, \"\")",
      "run_as_root            = optional(bool, false)",
      "run_as                 = optional(string, \"ec2-user\")",
      "maximum_count          = number",
      "ephemeral              = optional(bool, false)",
      "jit_config_enabled     = optional(bool, null)",
      "auto_update_disabled   = optional(bool, false)",
      "hooks = optional(object({",
      "job_started   = optional(string, \"\")",
      "job_completed = optional(string, \"\")",
      "iam = optional(object({",
      "role = optional(object({",
      "managed_policy_arns          = optional(map(string), {})",
      "additional_trust_policy_json = optional(string, null)",
      "path                         = optional(string, null)",
      "permissions_boundary         = optional(string, null)",
      "github = optional(object({",
      "organization_runners = optional(bool, false)",
      "lambda = optional(object({",
      "queue = optional(object({",
      "delay_webhook_event            = optional(number, 30)",
      "job_queue_retention_in_seconds = optional(number, 86400)",
      "event_source_mapping = optional(object({",
      "batch_size                         = optional(number, null)",
      "maximum_batching_window_in_seconds = optional(number, null)",
      "redrive_build_queue = optional(object({",
      "enabled         = bool",
      "maxReceiveCount = number",
      "scale_up = optional(object({",
      "reserved_concurrent_executions = optional(number, 1)",
      "job_queued_check_enabled       = optional(bool, null)",
      "scale_down = optional(object({",
      "schedule_expression             = optional(string, \"cron(*/5 * * * ? *)\")",
      "minimum_running_time_in_minutes = optional(number, null)",
      "idle_config = optional(list(object({",
      "cron             = string",
      "timeZone         = string",
      "idleCount        = number",
      "evictionStrategy = optional(string, \"oldest_first\")",
      "pool = optional(object({",
      "config = optional(list(object({",
      "schedule_expression          = string",
      "schedule_expression_timezone = optional(string)",
      "size                         = number",
      "runner_owner = optional(string, null)",
      "job_retry = optional(object({",
      "enabled          = optional(bool, false)",
      "delay_in_seconds = optional(number, 300)",
      "delay_backoff    = optional(number, 2)",
      "max_attempts     = optional(number, 1)",
      "memory_size                    = optional(number, 256)",
      "timeout                        = optional(number, 30)",
      "ssm = optional(object({",
      "kms_key = optional(object({",
      "parameters = optional(object({",
      "housekeeper = optional(object({",
      "observability = optional(object({",
      "logs = optional(object({",
      "blocked_keys = optional(list(string), [])",
      "restricted_keys = optional(map(object({",
      "allowed = optional(list(string), [])",
      "denied  = optional(list(string), [])",
      "max     = optional(string, null)",
      "compute_provider = object({",
      "ec2 = optional(object({",
      "metadata_options = optional(object({",
      "instance_metadata_tags      = optional(string, \"enabled\")",
      "http_endpoint               = optional(string, \"enabled\")",
      "http_tokens                 = optional(string, \"required\")",
      "http_put_response_hop_limit = optional(number, 1)",
      "ami = optional(object({",
      "filter = optional(map(list(string)), { state = [\"available\"] })",
      "owners = optional(list(string), [\"amazon\"])",
      "id_ssm_parameter = optional(object({",
      "kms_key = optional(object({",
      "arn = string",
      "block_device_mappings = optional(list(object({",
      "delete_on_termination      = optional(bool, true)",
      "device_name                = optional(string, \"/dev/xvda\")",
      "encrypted                  = optional(bool, true)",
      "iops                       = optional(number)",
      "kms_key_id                 = optional(string)",
      "snapshot_id                = optional(string)",
      "throughput                 = optional(number)",
      "volume_initialization_rate = optional(number)",
      "volume_size                = number",
      "volume_type                = optional(string, \"gp3\")",
      "create_service_linked_role_spot = optional(bool, false)",
      "credit_specification            = optional(string, null)",
      "ebs_optimized                   = optional(bool, false)",
      "cloudwatch_agent = optional(object({",
      "config  = optional(string, null)",
      "binaries_syncer = optional(object({",
      "detailed_monitoring_enabled = optional(bool, false)",
      "ssm_enabled                 = optional(bool, false)",
      "user_data = optional(object({",
      "enabled               = optional(bool, true)",
      "template              = optional(string, null)",
      "content               = optional(string, null)",
      "pre_install           = optional(string, \"\")",
      "post_install          = optional(string, \"\")",
      "debug_logging_enabled = optional(bool, false)",
      "instance_allocation_strategy  = optional(string, \"lowest-price\")",
      "instance_max_spot_price       = optional(string, null)",
      "instance_target_capacity_type = optional(string, \"spot\")",
      "instance_type_priorities      = optional(map(number), null)",
      "instance_types                = list(string)",
      "additional_security_group_ids = optional(list(string), [])",
      "instance_profile = optional(object({",
      "name = string",
      "enable_on_demand_failover_for_errors = optional(list(string), [])",
      "scale_errors = optional(list(string), [",
      "subnet_ids = optional(list(string), null)",
      "vpc_id     = optional(string, null)",
      "cpu_options = optional(object({",
      "core_count            = optional(number)",
      "threads_per_core      = optional(number)",
      "amd_sev_snp           = optional(string)",
      "nested_virtualization = optional(string)",
      "placement = optional(object({",
      "affinity                = optional(string)",
      "availability_zone       = optional(string)",
      "group_id                = optional(string)",
      "group_name              = optional(string)",
      "host_id                 = optional(string)",
      "host_resource_group_arn = optional(string)",
      "spread_domain           = optional(string)",
      "tenancy                 = optional(string)",
      "partition_number        = optional(number)",
      "license_specifications = optional(list(object({",
      "license_configuration_arn = string",
      "use_dedicated_host = optional(bool, false)",
      "log_files = optional(list(object({",
      "log_group_name   = string",
      "prefix_log_group = bool",
      "file_path        = string",
      "log_stream_name  = string",
      "log_class        = optional(string, \"STANDARD\")",
      "tags = optional(map(string), {})",
      "matcherConfig = object({",
      "labelMatchers           = list(list(string))",
      "exactMatch              = optional(bool, false)",
      "bidirectionalLabelMatch = optional(bool, false)",
      "priority                = optional(number, 999)",
      "enableDynamicLabels     = optional(bool, false)",
      "awsDynamicLabelsPolicy = optional(object({",
      "for runner_config in values(var.ec2_deployment_specs.runner_specs) :",
      "length(runner_config.compute_provider.ec2[*]) == 1",
      "length(runner_config.compute_provider.ec2.ami[*]) == 1",
      "&& length(runner_config.compute_provider.ec2.ami.id_ssm_parameter[*]) == 0,",
      "error_message = \"Forge EC2 runner_specs must configure a module-managed ami block; ami = null and external ami.id_ssm_parameter ownership are not supported.\"",
      "try(!runner_config.compute_provider.ec2.user_data.debug_logging_enabled, false)",
      "error_message = \"Forge EC2 runner_specs do not support user_data.debug_logging_enabled while the upstream v1 adapter is active.\"",
      "length(runner_config.compute_provider.ec2.instance_profile[*]) == 0",
      "&& length(runner_config.runner.iam.role[*]) == 0,",
      "error_message = \"Forge EC2 runner_specs do not support external runner.iam.role or compute_provider.ec2.instance_profile ownership while the upstream v1 adapter is active.\"",
      "length(runner_config.runner.tags) == 0",
      "&& length(runner_config.observability.logs.tags) == 0",
      "error_message = \"Forge EC2 runner_specs only support compute_provider.ec2.tags while the upstream v1 adapter is active; all other v2 per-lane tag maps must remain empty.\"",
      "runner_config.runner.iam.additional_trust_policy_json == null",
      "&& runner_config.job_retry.lambda.reserved_concurrent_executions == 1",
      "&& runner_config.ssm.kms_key == null",
      "error_message = \"Forge EC2 runner_specs do not support per-lane IAM trust/path/boundary, non-default job-retry Lambda reserved concurrency, or per-lane SSM KMS keys while the upstream v1 adapter is active.\"",
      "EC2 deployment configuration for GitHub Actions runners. The public runner",
      "- lambda_subnet_ids: Subnets where runner-related lambdas execute.",
      "These can be more permissive than the runner subnets.",
      "- subnet_ids       : Default subnets for EC2 runners.",
      "- vpc_id           : VPC that contains both runner and lambda subnets.",
      "- runner_specs     : Map of EC2 runner lanes.",
      "- runner          : Provider-neutral OS, architecture, labels, registration,",
      "- queue           : Webhook delay, retention, Lambda batching, and DLQ",
      "- job_retry       : Retry timing, attempts, and Lambda sizing.",
      "- matcherConfig   : Static and dynamic GitHub label matching.",
      "- compute_provider: Nested v2-compatible EC2 provider configuration.",
      "- tags/lambda/ssm/observability: Included for v2 contract compatibility.",
      "compute_provider.ec2 fields:",
      "- ami             : Upstream-compatible EC2 AMI configuration.",
      "The v7.10.1 compatibility adapter also requires external runner IAM ownership,",
      "variable \"github_webhook_relay\"",
      "Configuration for the (optional) webhook relay source module.",
      "If enabled=true we provision the API Gateway + source EventBridge forwarding rule.",
      "destination_event_bus_name must already exist or be created in the destination account (or via the destination submodule run there).",
      "enabled                     = bool",
      "destination_account_id      = optional(string)",
      "destination_event_bus_name  = optional(string)",
      "destination_region          = optional(string)",
      "destination_reader_role_arn = optional(string)",
      "default = {",
      "enabled                     = false",
      "destination_account_id      = \"\"",
      "destination_event_bus_name  = \"\"",
      "destination_region          = \"\"",
      "destination_reader_role_arn = \"\"",
      "variable \"log_level\"",
      "description = \"Log level for application logging (e.g., INFO, DEBUG, WARN, ERROR)\"",
      "variable \"logging_retention_in_days\"",
      "description = \"Logging retention period in days.\"",
      "variable \"tags\"",
      "output \"forge_core\"",
      "description = \"Core tenant-level metadata (non-sensitive).\"",
      "value = {",
      "tenant            = var.deployment_config.tenant",
      "runner_group_name = var.deployment_config.github.runner_group_name",
      "output \"forge_github_actions_job_logs\"",
      "description = \"GitHub Actions job log archival resources.\"",
      "bucket_arn               = try(module.github_actions_job_logs[0].s3_bucket_arn, null)",
      "bucket_kms_key_arn       = try(module.github_actions_job_logs[0].s3_bucket_kms_key_arn, null)",
      "sqs                      = try(module.github_actions_job_logs[0].sqs, null)",
      "internal_reader_role_arn = try(module.github_actions_job_logs[0].internal_s3_reader_role_arn, null)",
      "output \"forge_github_app\"",
      "description = \"GitHub App related outputs.\"",
      "installation_url = local.github_app_installation",
      "installation_id  = var.deployment_config.github_app.installation_id",
      "name             = var.deployment_config.github_app.name",
      "sensitive = true",
      "output \"forge_runners\"",
      "description = \"Combined runners output (EC2 + ARC)\"",
      "ec2 = {",
      "runners_arn_map    = try(module.ec2_runners[0].ec2_runners_arn_map, {})",
      "ami_name_map       = try(module.ec2_runners[0].ec2_runners_ami_name_map, {})",
      "subnet_cidr_blocks = try(module.ec2_runners[0].subnet_cidr_blocks, [])",
      "runner_labels      = try(module.ec2_runners[0].ec2_runners_labels_map, {})",
      "arc = {",
      "cluster_name       = try(module.arc_runners.arc_cluster_name, {})",
      "runners_arn_map    = try(module.arc_runners.arc_runners_arn_map, {})",
      "subnet_cidr_blocks = try(module.arc_runners.subnet_cidr_blocks, [])",
      "runner_labels      = try(module.arc_runners.arc_runners_labels_map, {})",
      "output \"forge_webhook_relay\"",
      "description = \"Webhook relay integration outputs.\"",
      "source_secret_arn      = try(module.github_webhook_relay[0].source_secret_arn, null)",
      "source_secret_role_arn = try(module.github_webhook_relay[0].source_secret_role_arn, null)",
      "source_secret_region   = try(module.github_webhook_relay[0].source_secret_region, null)",
    ]
  }

  assert {
    condition     = length(output.missing_input_variables) == 0
    error_message = "Interface contract is missing input variables: ${join(", ", output.missing_input_variables)}"
  }

  assert {
    condition     = length(output.unexpected_input_variables) == 0
    error_message = "Interface contract has unexpected input variables: ${join(", ", output.unexpected_input_variables)}"
  }

  assert {
    condition     = length(output.missing_output_values) == 0
    error_message = "Interface contract is missing outputs: ${join(", ", output.missing_output_values)}"
  }

  assert {
    condition     = length(output.unexpected_output_values) == 0
    error_message = "Interface contract has unexpected outputs: ${join(", ", output.unexpected_output_values)}"
  }

  assert {
    condition     = length(output.missing_interface_literals) == 0
    error_message = "Interface contract is missing expected variable/output source lines: ${join(", ", output.missing_interface_literals)}"
  }

  assert {
    condition = (
      output.expected_input_variable_count == 10
      && output.expected_output_value_count == 5
      && output.expected_interface_literal_count == 358
    )
    error_message = "Interface contract counts must remain pinned for inputs, outputs, and source literals."
  }
}
