---
# yamllint disable rule:comments
# yamllint disable rule:truthy
name: ClusterFuzzLite PR Fuzzing

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - renovatebot
    paths:
      - .clusterfuzzlite/**
      - .github/workflows/cflite_*.yml
      - modules/**/lambda/**
      - fuzz/**
      - pyproject.toml
      - uv.lock

permissions: {}

jobs:
  fuzz:
    name: Python fuzzers (${{ matrix.sanitizer }})
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Build fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: python
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: ${{ matrix.sanitizer }}
          keep-unaffected-fuzz-targets: true

      - name: Run fuzzers (${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 120
          mode: code-change
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
